### ISSUE TITLE
Naming convention for DICOM controlled vocabulary terms

### ISSUE THREAD

**Issue by khelm** [incf-nidash/dicom-ontology#1]
I'm finishing up code to create a DICOM turtle file and a few issues have come up that need discussion. 

The questions are: 
1) Do we want the tag term in camelcase as the ID or do we want numerical ID's at the outset?  
2) If numerical, should we use the dicom tag as the ID, e.g. (0018, 003F) -> dicom_0018003F

Neither one is a problem as I have code that will take the DICOM tag label "Spectroscopy Acquisition Out-of-plane Phase Steps" and turn it into "spectroscopyAcquisitionOutOfPlanePhaseSteps" already written.

Note that while we can point to the Neurolex ID's, we can't use them as the ID, because there are now more DICOM terms available than when I first put the terms in Neurolex.

**Comment by cmaumet** [comment]
Hi @khelm! Thank you for sharing those! Here are my thoughts: 

> 1. Do we want the tag term in camelcase as the ID or do we want numerical ID's at the outset?

Correct me if I am wrong but because the DICOM terms are a direct mapping of the existing DICOM specification I think that we will probably not have to discuss the terms/definitions but only the overall organisation? If that's right then I think using numerical IDs from the start makes sense.

> 2. If numerical, should we use the dicom tag as the ID, e.g. (0018, 003F) -> dicom_0018003F

Yes, I would vote for reusing the existing DICOM tags.

> Note that while we can point to the Neurolex ID's, we can't use them as the ID, because there are now more DICOM terms available than when I first put the terms in Neurolex.

Could we reuse Neurolex IDs for the terms that are available in there? Or at least link to them with `isSameAs`?

Shall we add these questions to the agenda of our next NIDM call to open the discussion to everyone?

**Comment by khelm** [comment]
Hi @cmaumet 

I think using the tag as an ID makes the most sense from a usability standpoint.  My code adds the Neurolex ID to the term if it exists, if not it just skips it, so dealing with missing Neurolex IDs is no problem.

**Comment by jbpoline** [comment]
I suppose using the ID doesn't prevent to have a "label"  or "PreferredLabel" attribute ?

**Comment by khelm** [comment]
No, it doesn't.  The goal is to eventually switch the reference of NIDM experiment terms from the label to a numerical ID, as it's done in NIDM-Results.  That's the last step though, after the terms are finalized.  In the case of the DICOM terms, however, the tags already form a natural ID = (0018,0081) could be dicom_00180081, for example, and the label would be "Echo Time".

**Comment by khelm** [comment]
This issue is now being discussed in: https://github.com/incf-nidash/dicom-ontology/issues/3 so I will close this one.
